### ISSUE TITLE
Support for branches

### ISSUE THREAD

**Issue by dholmen** [enonic/app-gitpull#8] opened 2019-04-10 11:49 UTC
Configurable support for branches would be really useful, and the last piece of the puzzle in order to enable us to use this app in our setup.

For example:
```
prod.url = https://some/git/url
prod.user = username
prod.password = password
prod.dir = ${xp.home}/config
**prod.branch = master**
```

**Comment by sigdestad** [comment] 2019-04-12 08:18
Seems like an interesting approach..

**Comment by rymsha** [comment] 2020-11-16 08:40
duplicate of #3

**Closed** 2020-11-17 12:35 UTC
Labels: enhancement
